### Read in Data
rm(list=ls())
newdata <- read.csv(file="D:/R Input files/CSAT Working File.csv", header=TRUE, sep=",")
head(newdata,15)
dim(newdata)
str(newdata)

###Subject_Fin

library("tm")
library("tmap")
newdata$Subject_Fin   <- toupper(newdata$Note)   ## to convert text into upper case
newdata$Subject_Fin   <- removePunctuation(newdata$Subject_Fin)  ## to remove symbols
newdata$Subject_Fin   <- gsub("\\s+"," ",newdata$Subject_Fin) ## to remove extra spaces b/w words




###FLAG Fields
newdata$ABLEFLAG = grepl("ABLE",newdata$Subject_Fin)
newdata$ACCOUNTFLAG = grepl("ACCOUNT",newdata$Subject_Fin)
newdata$ACKNOWLEDGEFLAG = grepl("ACKNOWLEDGE",newdata$Subject_Fin)
newdata$ACTIVATIONFLAG = grepl("ACTIVATION",newdata$Subject_Fin)
newdata$ADMINFLAG = grepl("ADMIN",newdata$Subject_Fin)
newdata$ADMINISTRATORFLAG = grepl("ADMINISTRATOR",newdata$Subject_Fin)
newdata$AFFECTINGFLAG = grepl("AFFECTING",newdata$Subject_Fin)
newdata$AGAINFLAG = grepl("AGAIN",newdata$Subject_Fin)
newdata$ALERTFLAG = grepl("ALERT",newdata$Subject_Fin)
newdata$ALLFLAG = grepl("ALL",newdata$Subject_Fin)
newdata$AMAZINGFLAG = grepl("AMAZING",newdata$Subject_Fin)
newdata$ANYONEFLAG = grepl("ANYONE",newdata$Subject_Fin)
newdata$ANYUPDATEFLAG = grepl("ANY UPDATE",newdata$Subject_Fin)
newdata$APPRECIATEFLAG = grepl("APPRECIATE",newdata$Subject_Fin)
newdata$AREAFLAG = grepl("AREA",newdata$Subject_Fin)
newdata$AREFLAG = grepl("ARE",newdata$Subject_Fin)
newdata$AROUNDFLAG = grepl("AROUND",newdata$Subject_Fin)
newdata$ASSISTANCEFLAG = grepl("ASSISTANCE",newdata$Subject_Fin)
newdata$ASSISTFLAG = grepl("ASSIST",newdata$Subject_Fin)
newdata$ATTEMPTFLAG = grepl("ATTEMPT",newdata$Subject_Fin)
newdata$AWFULFLAG = grepl("AWFUL",newdata$Subject_Fin)
newdata$BADFLAG = grepl("BAD",newdata$Subject_Fin)
newdata$CALLFLAG = grepl("CALL",newdata$Subject_Fin)
newdata$CANFLAG = grepl("CAN",newdata$Subject_Fin)
newdata$CANANYONEFLAG = grepl("CAN ANYONE",newdata$Subject_Fin)
newdata$CANNOTFLAG = ifelse(grepl("CAN NOT",newdata$Subject_Fin),TRUE,
                                 ifelse(grepl("CANNOT",newdata$Subject_Fin),TRUE,
                                        ifelse(grepl("CANT",newdata$Subject_Fin),TRUE,FALSE)))
newdata$CANSOMEONEFLAG = grepl("CAN SOMEONE",newdata$Subject_Fin)
newdata$CANYOUFLAG = ifelse(grepl("CAN YOU",newdata$Subject_Fin),TRUE,
                                 ifelse(grepl("CANYOU",newdata$Subject_Fin),TRUE,FALSE))
newdata$CAREFLAG = grepl("CARE",newdata$Subject_Fin)
newdata$CHANGEFLAG = grepl("CHANGE",newdata$Subject_Fin)
newdata$CHECKFLAG = grepl("CHECK",newdata$Subject_Fin)
newdata$CLOSEDFLAG = grepl("CLOSED",newdata$Subject_Fin)
newdata$CLOSEFLAG = grepl("CLOSE",newdata$Subject_Fin)
newdata$CLOSINGFLAG = grepl("CLOSING",newdata$Subject_Fin)
newdata$CODEFLAG = grepl("CODE",newdata$Subject_Fin)
newdata$COMPLETEDFLAG = grepl("COMPLETED",newdata$Subject_Fin)
newdata$COMPLETEFLAG = grepl("COMPLETE",newdata$Subject_Fin)
newdata$COMPUTER = grepl("COMPUTER",newdata$Subject_Fin)
newdata$CONFIGUREFLAG = grepl("CONFIGURE",newdata$Subject_Fin)
newdata$CONFIRMATIONFLAG = grepl("CONFIRMATION",newdata$Subject_Fin)
newdata$CONFIRMFLAG = grepl("CONFIRM",newdata$Subject_Fin)
newdata$CONNECTFLAG = grepl("CONNECT",newdata$Subject_Fin)
newdata$CONNECTINGFLAG = grepl("CONNECTING",newdata$Subject_Fin)
newdata$CONTACTFLAG = grepl("CONTACT",newdata$Subject_Fin)
newdata$CONTINUOUSFLAG = grepl("CONTINUOUS",newdata$Subject_Fin)
newdata$CUSTOMERFLAG = grepl("CUSTOMER",newdata$Subject_Fin)
newdata$DESKFLAG = grepl("DESK",newdata$Subject_Fin)
newdata$DIDNOTFLAG = ifelse(grepl("DID NOT",newdata$Subject_Fin),TRUE,
                                 ifelse(grepl("DIDNOT",newdata$Subject_Fin),TRUE,
                                        ifelse(grepl("DIDNT",newdata$Subject_Fin),TRUE,FALSE)))
newdata$DISAPPOINTEDFLAG = ifelse(grepl("DISAPPOINTED",newdata$Subject_Fin),TRUE,
                                       ifelse(grepl("DISSAPOINTED",newdata$Subject_Fin),TRUE,FALSE))
newdata$DISAPPOINTINGFLAG = grepl("DISAPPOINTING",newdata$Subject_Fin)
newdata$DISSAPOINTFLAG = grepl("DISSAPOINT",newdata$Subject_Fin)
newdata$DISATISFIEDFLAG = grepl("DISATISFIED",newdata$Subject_Fin)
newdata$DOESNOTFLAG = ifelse(grepl("DOES NOT",newdata$Subject_Fin),TRUE,
                                  ifelse(grepl("DOESNOT",newdata$Subject_Fin),TRUE,
                                         ifelse(grepl("DOESNT",newdata$Subject_Fin),TRUE,FALSE)))
newdata$DONEFLAG = grepl("DONE",newdata$Subject_Fin)
newdata$DONOTFLAG = ifelse(grepl("DO NOT",newdata$Subject_Fin),TRUE,
                                ifelse(grepl("DONOT",newdata$Subject_Fin),TRUE,
                                       ifelse(grepl("DONT",newdata$Subject_Fin),TRUE,FALSE)))
newdata$DOWNFLAG = grepl("DOWN",newdata$Subject_Fin)
newdata$DOWNLOADFLAG = grepl("DOWNLOAD",newdata$Subject_Fin)
newdata$ENDFLAG = grepl("END",newdata$Subject_Fin)
newdata$ERRORFLAG = grepl("ERROR",newdata$Subject_Fin)
newdata$EXCELLENTFLAG = grepl("EXCELLENT",newdata$Subject_Fin)
newdata$EXPERIENCEFLAG = grepl("EXPERIENCE",newdata$Subject_Fin)
newdata$EXTREMELYFLAG = grepl("EXTREMELY",newdata$Subject_Fin)
newdata$FINEFLAG = grepl("FINE",newdata$Subject_Fin)
newdata$FINISHFLAG = grepl("FINISH",newdata$Subject_Fin)
newdata$FOLDERFLAG = grepl("FOLDER",newdata$Subject_Fin)
newdata$FOLLOWUPFLAG = grepl("FOLLOW UP",newdata$Subject_Fin)
newdata$FORFLAG = grepl("FOR",newdata$Subject_Fin)
newdata$FOUNDFLAG = grepl("FOUND",newdata$Subject_Fin)
newdata$GETFLAG = grepl("GET",newdata$Subject_Fin)
newdata$GETTINGFLAG = grepl("GETTING",newdata$Subject_Fin)
newdata$GOODFLAG = grepl("GOOD",newdata$Subject_Fin)
newdata$GREATFLAG = grepl("GREAT",newdata$Subject_Fin)
newdata$GREYFLAG = grepl("GREY",newdata$Subject_Fin)
newdata$HADFLAG = grepl("HAD",newdata$Subject_Fin)
newdata$HAPPYFLAG = grepl("HAPPY",newdata$Subject_Fin)
newdata$HASFLAG = grepl("HAS",newdata$Subject_Fin)
newdata$HAPPYFLAG = grepl("HAPPY",newdata$Subject_Fin)
newdata$HAVEFLAG = grepl("HAVE",newdata$Subject_Fin)
newdata$HAVENOTFLAG = ifelse(grepl("HAVE NOT",newdata$Subject_Fin),TRUE,
                                  ifelse(grepl("HAVENOT",newdata$Subject_Fin),TRUE,
                                         ifelse(grepl("HAVENT",newdata$Subject_Fin),TRUE,FALSE)))
newdata$HELPFLAG = grepl("HELP",newdata$Subject_Fin)
newdata$HELPFULFLAG = grepl("HELPFUL",newdata$Subject_Fin)
newdata$HIGHERFLAG = grepl("HIGHER",newdata$Subject_Fin)
newdata$HORRIBLEFLAG = grepl("HORRIBLE",newdata$Subject_Fin)
newdata$IAMFLAG = grepl("I AM",newdata$Subject_Fin)
newdata$IEFLAG = grepl("IE",newdata$Subject_Fin)
newdata$INSTALLFLAG = grepl("INSTALL",newdata$Subject_Fin)
newdata$INTERNETEXPLORERFLAG = grepl("INTERNET EXPLORER",newdata$Subject_Fin)
newdata$IRRITATINGFLAG = grepl("IRRITATING",newdata$Subject_Fin)
newdata$ISSUEFLAG = grepl("ISSUE",newdata$Subject_Fin)
newdata$JOBFLAG = grepl("JOB",newdata$Subject_Fin)
newdata$KNOWFLAG = grepl("KNOW",newdata$Subject_Fin)
newdata$LAPTOPFLAG = grepl("LAPTOP",newdata$Subject_Fin)
newdata$LATEFLAG = grepl("LATE",newdata$Subject_Fin)
newdata$LATESTFLAG = grepl("LATEST",newdata$Subject_Fin)
newdata$LETMEKNOWFLAG = grepl("LET ME KNOW",newdata$Subject_Fin)
newdata$LEVELFLAG = grepl("LEVEL",newdata$Subject_Fin)
newdata$LOOKFLAG = grepl("LOOK",newdata$Subject_Fin)
newdata$LOCALFLAG = grepl("LOCAL",newdata$Subject_Fin)
newdata$LOCATIONFLAG = grepl("LOCATION",newdata$Subject_Fin)
newdata$LOCKEDFLAG = grepl("LOCKED",newdata$Subject_Fin)
newdata$LOCKFLAG = grepl("LOCK",newdata$Subject_Fin)
newdata$LOGINFLAG = ifelse(grepl("LOGIN",newdata$Subject_Fin),TRUE,
                                ifelse(grepl("LOG IN",newdata$Subject_Fin),TRUE,
                                       ifelse(grepl("LOG-IN",newdata$Subject_Fin),TRUE,FALSE)))
newdata$LONGFLAG = grepl("LONG",newdata$Subject_Fin)
newdata$MOVEMENTFLAG = grepl("MOVEMENT",newdata$Subject_Fin)
newdata$MSOFFICEFLAG = ifelse(grepl("MS OFFICE",newdata$Subject_Fin),TRUE,
                                   ifelse(grepl("MSOFFICE",newdata$Subject_Fin),TRUE,
                                          ifelse(grepl("MS-OFFICE",newdata$Subject_Fin),TRUE,FALSE)))
newdata$MULTIPLEFLAG = grepl("MULTIPLE",newdata$Subject_Fin)
newdata$NEEDFLAG = grepl("NEED",newdata$Subject_Fin)
newdata$NEEDASSISTANCEFLAG = grepl("NEED ASSISTANCE",newdata$Subject_Fin)
newdata$NOBODYHASFLAG = grepl("NOBODY HAS",newdata$Subject_Fin)
newdata$NOFLAG = grepl("NO",newdata$Subject_Fin)
newdata$NOPROPERFLAG = grepl("NO PROPER",newdata$Subject_Fin)
newdata$NORESPONSEFLAG = grepl("NO RESPONSE",newdata$Subject_Fin)
newdata$NOTRESPONDINGFLAG = grepl("NOT RESPONDING",newdata$Subject_Fin)
newdata$NOTESFLAG = grepl("NOTES",newdata$Subject_Fin)
newdata$NOTFLAG = grepl("NOT",newdata$Subject_Fin)
newdata$NOTPROPERFLAG = grepl("NOT PROPER",newdata$Subject_Fin)
newdata$NOTRESPONDEDFLAG = grepl("NOT RESPONDED",newdata$Subject_Fin)
newdata$NOTWORKINGFLAG = grepl("NOT WORKING",newdata$Subject_Fin)
newdata$NOTHAPPYFLAG = grepl("NOT HAPPY",newdata$Subject_Fin)
newdata$NOTHINGFLAG = grepl("NOTHING",newdata$Subject_Fin)
newdata$NOTSATISFIEDFLAG = grepl("NOT SATISFIED",newdata$Subject_Fin)
newdata$NOUPDATEFLAG = grepl("NO UPDATE",newdata$Subject_Fin)
newdata$NOWFLAG = grepl("NOW",newdata$Subject_Fin)
newdata$OFFICEFLAG = grepl("OFFICE",newdata$Subject_Fin)
newdata$OLDFLAG = grepl("OLD",newdata$Subject_Fin)
newdata$ONFLAG = grepl("ON",newdata$Subject_Fin)
newdata$ONGOINGFLAG = ifelse(grepl("ON GOING",newdata$Subject_Fin),TRUE,
                                  ifelse(grepl("ONGOING",newdata$Subject_Fin),TRUE,
                                         ifelse(grepl("ON-GOING",newdata$Subject_Fin),TRUE,FALSE)))
newdata$OPTIONFLAG = grepl("OPTION",newdata$Subject_Fin)
newdata$OSFLAG = grepl("OS",newdata$Subject_Fin)
newdata$OUTAGEFLAG = ifelse(grepl("OUTAGE",newdata$Subject_Fin),TRUE,
                                 ifelse(grepl("OUT AGE",newdata$Subject_Fin),TRUE,
                                        ifelse(grepl("OUT-AGE",newdata$Subject_Fin),TRUE,FALSE)))
newdata$OUTFLAG = grepl("OUT",newdata$Subject_Fin)
newdata$PASSWORDFLAG = ifelse(grepl("PASSWORD",newdata$Subject_Fin),TRUE,
                                   ifelse(grepl("PASS WORD",newdata$Subject_Fin),TRUE,
                                          ifelse(grepl("PASS-WORD",newdata$Subject_Fin),TRUE,FALSE)))
newdata$PENDINGFLAG = grepl("PENDING",newdata$Subject_Fin)
newdata$PERFORMANCEFLAG = grepl("PERFORMANCE",newdata$Subject_Fin)
newdata$PHONEFLAG = grepl("PHONE",newdata$Subject_Fin)
newdata$PICKUPFLAG = grepl("PICK UP",newdata$Subject_Fin)
newdata$POORFLAG = grepl("POOR",newdata$Subject_Fin)
newdata$POSTEDFLAG = grepl("POSTED",newdata$Subject_Fin)
newdata$POSTFLAG = grepl("POST",newdata$Subject_Fin)
newdata$PRINTFLAG = grepl("PRINT",newdata$Subject_Fin)
newdata$PRINTERFLAG = grepl("PRINTER",newdata$Subject_Fin)
newdata$PRIORITYFLAG = grepl("PRIORITY",newdata$Subject_Fin)
newdata$PROBLEMFLAG = grepl("PROBLEM",newdata$Subject_Fin)
newdata$PROCEEDFLAG = grepl("PROCEED",newdata$Subject_Fin)
newdata$PROGRAMFLAG = grepl("PROGRAM",newdata$Subject_Fin)
newdata$PROGRESSFLAG = grepl("PROGRESS",newdata$Subject_Fin)
newdata$PROLONGFLAG = grepl("PROLONG",newdata$Subject_Fin)
newdata$PROPERFLAG = grepl("PROPER",newdata$Subject_Fin)
newdata$PROVIDEDFLAG = grepl("PROVIDED",newdata$Subject_Fin)
newdata$PROVIDEFLAG = grepl("PROVIDE",newdata$Subject_Fin)
newdata$PURPOSEFLAG = grepl("PURPOSE",newdata$Subject_Fin)
newdata$QUICKFLAG = grepl("QUICK",newdata$Subject_Fin)
newdata$REACHFLAG = grepl("REACH",newdata$Subject_Fin)
newdata$REBOOTFLAG = ifelse(grepl("REBOOT",newdata$Subject_Fin),TRUE,
                                 ifelse(grepl("RE BOOT",newdata$Subject_Fin),TRUE,
                                        ifelse(grepl("RE-BOOT",newdata$Subject_Fin),TRUE,FALSE)))
newdata$RECEIVEDFLAG = grepl("RECEIVED",newdata$Subject_Fin)
newdata$RECEIVEFLAG = grepl("RECEIVE",newdata$Subject_Fin)
newdata$REINSTALLFLAG = ifelse(grepl("REINSTALL",newdata$Subject_Fin),TRUE,
                                    ifelse(grepl("RE INSTALL",newdata$Subject_Fin),TRUE,
                                           ifelse(grepl("RE-INSTALL",newdata$Subject_Fin),TRUE,FALSE)))
newdata$REQUESTFLAG = grepl("REQUEST",newdata$Subject_Fin)
newdata$RESETFLAG = ifelse(grepl("RESET",newdata$Subject_Fin),TRUE,
                                ifelse(grepl("RE SET",newdata$Subject_Fin),TRUE,
                                       ifelse(grepl("RE-SET",newdata$Subject_Fin),TRUE,FALSE)))
newdata$RESETTINGFLAG = grepl("RESETTING",newdata$Subject_Fin)
newdata$RESOLUTIONFLAG = grepl("RESOLUTION",newdata$Subject_Fin)
newdata$RESOLVEDFLAG = grepl("RESOLVED",newdata$Subject_Fin)
newdata$RESOLVEFLAG = grepl("RESOLVE",newdata$Subject_Fin)
newdata$RESOLVINGFLAG = grepl("RESOLVING",newdata$Subject_Fin)
newdata$RESPONDEDFLAG = grepl("RESPONDED",newdata$Subject_Fin)
newdata$RESPONDFLAG = grepl("RESPOND",newdata$Subject_Fin)
newdata$RESPONDINGFLAG = grepl("RESPONDING",newdata$Subject_Fin)
newdata$RESPONSEFLAG = grepl("RESPONSE",newdata$Subject_Fin)
newdata$RESTARTED = ifelse(grepl("RESTARTED",newdata$Subject_Fin),TRUE,
                                ifelse(grepl("RE STARTED",newdata$Subject_Fin),TRUE,
                                       ifelse(grepl("RE-STARTED",newdata$Subject_Fin),TRUE,FALSE)))
newdata$RESTOREDFLAG = grepl("RESTORED",newdata$Subject_Fin)
newdata$RESTOREFLAG = grepl("RESTORE",newdata$Subject_Fin)
newdata$RIGHTFLAG = grepl("RIGHT",newdata$Subject_Fin)
newdata$SATISFIEDFLAG = grepl("SATISFIED",newdata$Subject_Fin)
newdata$SERVICEFLAG = grepl("SERVICE",newdata$Subject_Fin)
newdata$SOFTWAREFLAG = grepl("SOFTWARE",newdata$Subject_Fin)
newdata$SOLONGFLAG = grepl("SO LONG",newdata$Subject_Fin)
newdata$SOLUTIONFLAG = grepl("SOLUTION",newdata$Subject_Fin)
newdata$SOMEONEFLAG = grepl("SOMEONE",newdata$Subject_Fin)
newdata$STATUSFLAG = grepl("STATUS",newdata$Subject_Fin)
newdata$STILLDOESNTWORKFLAG = ifelse(grepl("STILL DOES NOT WORK",newdata$Subject_Fin),TRUE,
                                          ifelse(grepl("STILL DOESNOT WORK",newdata$Subject_Fin),TRUE,
                                                 ifelse(grepl("STILL DOESNT WORK",newdata$Subject_Fin),TRUE,FALSE)))
newdata$STILLFLAG = grepl("STILL",newdata$Subject_Fin)
newdata$STILLNOTWORKINGFLAG = grepl("STILL NOT WORKING",newdata$Subject_Fin)
newdata$SUCCESSFLAG = grepl("SUCCESS",newdata$Subject_Fin)
newdata$SUCCESSFULFLAG = grepl("SUCCESSFUL",newdata$Subject_Fin)
newdata$SUCCESSFULLYFLAG = grepl("SUCCESSFULLY",newdata$Subject_Fin)
newdata$SUPPORTFLAG = grepl("SUPPORT",newdata$Subject_Fin)
newdata$SUREFLAG = grepl("SURE",newdata$Subject_Fin)
newdata$SYSTEMFLAG = grepl("SYSTEM",newdata$Subject_Fin)
newdata$TAKINGFLAG = grepl("TAKING",newdata$Subject_Fin)
newdata$TERRIBLEFLAG = grepl("TERRIBLE",newdata$Subject_Fin)
newdata$THANKYOUFLAG = ifelse(grepl("THANK YOU",newdata$Subject_Fin),TRUE,
                                   ifelse(grepl("THANKYOU",newdata$Subject_Fin),TRUE,FALSE))
newdata$THANKSFLAG = grepl("THANKS",newdata$Subject_Fin)
newdata$TICKETFLAG = grepl("TICKET",newdata$Subject_Fin)
newdata$TIMESFLAG = grepl("TIMES",newdata$Subject_Fin)
newdata$TODAYFLAG = grepl("TODAY",newdata$Subject_Fin)
newdata$TONERFLAG = grepl("TONER",newdata$Subject_Fin)
newdata$TOOKFLAG = grepl("TOOK",newdata$Subject_Fin)
newdata$TURNFLAG = grepl("TURN",newdata$Subject_Fin)
newdata$UNABLEFLAG = ifelse(grepl("UNABLE",newdata$Subject_Fin),TRUE,
                                 ifelse(grepl("UN ABLE",newdata$Subject_Fin),TRUE,
                                        ifelse(grepl("UN-ABLE",newdata$Subject_Fin),TRUE,FALSE)))
newdata$UNHAPPYFLAG = grepl("UNHAPPY",newdata$Subject_Fin)
newdata$UNSATISFIEDFLAG = grepl("UNSATISFIED",newdata$Subject_Fin)
newdata$UPDATEFLAG = grepl("UPDATE",newdata$Subject_Fin)
newdata$UPDATEDFLAG = grepl("UPDATED",newdata$Subject_Fin)
newdata$USERFLAG = grepl("USER",newdata$Subject_Fin)
newdata$VERSIONFLAG = grepl("VERSION",newdata$Subject_Fin)
newdata$VERYFLAG = grepl("VERY",newdata$Subject_Fin)
newdata$VERYBADFLAG = grepl("VERY BAD",newdata$Subject_Fin)
newdata$VERYDISATISFIEDFLAG = grepl("VERY DISATISFIED",newdata$Subject_Fin)
newdata$VERYUNHAPPYFLAG = grepl("VERY UNHAPPY",newdata$Subject_Fin)
newdata$VERYUNSATISFIEDFLAG = grepl("VERY UNSATISFIED",newdata$Subject_Fin)
newdata$VERYHELPFULFLAG = grepl("VERY HELPFUL",newdata$Subject_Fin)
newdata$VERYHAPPYFLAG = grepl("VERY HAPPY",newdata$Subject_Fin)
newdata$VERYGOODFLAG = grepl("VERY GOOD",newdata$Subject_Fin)
newdata$WAITINGFLAG = grepl("WAITING",newdata$Subject_Fin)
newdata$WASNOTFLAG = ifelse(grepl("WAS NOT",newdata$Subject_Fin),TRUE,
                                 ifelse(grepl("WASNOT",newdata$Subject_Fin),TRUE,
                                        ifelse(grepl("WASNT",newdata$Subject_Fin),TRUE,FALSE)))
newdata$WEAREFLAG = grepl("WE ARE",newdata$Subject_Fin)
newdata$WHYWONTFLAG = grepl("WHY WONT",newdata$Subject_Fin)
newdata$WILLANYONEFLAG = grepl("WILL ANYONE",newdata$Subject_Fin)
newdata$WILLYOUFLAG = grepl("WILL YOU",newdata$Subject_Fin)
newdata$WINGFLAG = grepl("WING",newdata$Subject_Fin)
newdata$WITHOUTFLAG = grepl("WITHOUT",newdata$Subject_Fin)
newdata$WONDERFLAG = grepl("WONDER",newdata$Subject_Fin)
newdata$WONDERFULFLAG = grepl("WONDERFUL",newdata$Subject_Fin)
newdata$WORKEDFLAG = grepl("WORKED",newdata$Subject_Fin)
newdata$WORKFLAG = grepl("WORK",newdata$Subject_Fin)
newdata$WORKINGFLAG = grepl("WORKING",newdata$Subject_Fin)
newdata$WORKINGONFLAG = grepl("WORKING ON",newdata$Subject_Fin)
newdata$WORSTFLAG = grepl("WORST",newdata$Subject_Fin)
newdata$YETTOGETFLAG = grepl("YET TO GET",newdata$Subject_Fin)
newdata$YOUFLAG = grepl("YOU",newdata$Subject_Fin)
newdata$YOUHAVEFLAG = grepl("YOU HAVE",newdata$Subject_Fin)
newdata$YOURASSISTANCEFLAG = grepl("YOUR ASSISTANCE",newdata$Subject_Fin)
newdata$YOURFLAG = grepl("YOUR",newdata$Subject_Fin)

###NEGATIVE KEYWORDVAR

newdata$KEYWORDVAR  = ''
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & (newdata$AWFULFLAG == 'TRUE' | newdata$BADFLAG == 'TRUE' | newdata$DISAPPOINTEDFLAG == 'TRUE'| newdata$DISATISFIEDFLAG == 'TRUE' | newdata$IRRITATINGFLAG == 'TRUE' | newdata$HORRIBLEFLAG == 'TRUE' | newdata$NOFLAG == 'TRUE' | newdata$NOTFLAG == 'TRUE' | newdata$NOTPROPER == 'TRUE' | newdata$NOTHAPPY == 'TRUE' | newdata$POORFLAG == 'TRUE' | newdata$TERRIBLEFLAG == 'TRUE' | newdata$UNSATISFIEDFLAG == 'TRUE' | newdata$UNHAPPYFLAG == 'TRUE' | newdata$VERYBADFLAG == 'TRUE' | newdata$VERYUNHAPPYFLAG == 'TRUE' | newdata$VERYUNSATISFIEDFLAG == 'TRUE' | newdata$VERYDISATISFIEDFLAG == 'TRUE' | newdata$WORSTFLAG == 'TRUE') & (newdata$EXPERIENCEFLAG == 'TRUE' | newdata$SERVICEFLAG == 'TRUE' | newdata$ASSISTANCEFLAG == 'TRUE' | newdata$PERFORMANCEFLAG == 'TRUE' | newdata$WORKINGFLAG == 'TRUE' | newdata$SATISFIEDFLAG == 'TRUE' | newdata$RESPONSEFLAG == 'TRUE' | newdata$STATUSFLAG == 'TRUE' | newdata$RESPONSEFLAG == 'TRUE' | newdata$RESPONDEDFLAG == 'TRUE' | newdata$RESPONDINGFLAG == 'TRUE' | newdata$UPDATEFLAG == 'TRUE'),'AAACAZ BAD CUSTOMER SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & (newdata$AWFULFLAG == 'TRUE' | newdata$BADFLAG == 'TRUE' | newdata$DISAPPOINTEDFLAG == 'TRUE'| newdata$DISATISFIEDFLAG == 'TRUE' | newdata$IRRITATINGFLAG == 'TRUE' | newdata$HORRIBLEFLAG == 'TRUE' |  newdata$NOTPROPER == 'TRUE' | newdata$NOTHAPPY == 'TRUE' | newdata$POORFLAG == 'TRUE' | newdata$TERRIBLEFLAG == 'TRUE' | newdata$UNSATISFIEDFLAG == 'TRUE' | newdata$UNHAPPYFLAG == 'TRUE' | newdata$VERYBADFLAG == 'TRUE' | newdata$VERYUNHAPPYFLAG == 'TRUE' | newdata$VERYUNSATISFIEDFLAG == 'TRUE' | newdata$VERYDISATISFIEDFLAG == 'TRUE' | newdata$WORSTFLAG == 'TRUE'),'AAACAZ BAD',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$WILLYOUFLAG == 'TRUE' & newdata$RESPONDFLAG == 'TRUE','AAAAAA WILL YOU RESPOND',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$RESPONDFLAG == 'TRUE' & newdata$POORFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AAAAAB RESPOND POOR CUSTOMER SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$RESPONDFLAG == 'TRUE' & newdata$POORFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AAAAAC RESPOND POOR SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$POORFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AAAAAD POOR CUSTOMER SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$WHYWONTFLAG == 'TRUE' & newdata$ANYONEFLAG == 'TRUE' & newdata$RESPONDFLAG == 'TRUE','AAAAAE WHY WONT ANYONE RESPOND',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$WHYWONTFLAG == 'TRUE' & newdata$ANYONEFLAG == 'TRUE' & newdata$RESPONDFLAG == 'TRUE' & newdata$REQUESTFLAG == 'TRUE','AAAAAF WHY WONT ANYONE RESPOND REQUEST',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CANNOTFLAG == 'TRUE' & newdata$GETFLAG == 'TRUE' & newdata$RESPONSEFLAG == 'TRUE','AAAAAG CANNOT GET RESPONSE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$REQUESTFLAG == 'TRUE' & newdata$STATUSFLAG == 'TRUE' & newdata$CANNOTFLAG == 'TRUE' & newdata$GETFLAG == 'TRUE' & newdata$RESPONSEFLAG == 'TRUE','AAAAAH REQUEST STATUS CANNOT GET RESPONSE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOFLAG == 'TRUE' & newdata$RESPONSEFLAG == 'TRUE' & newdata$UPDATEFLAG == 'TRUE' & newdata$STATUSFLAG == 'TRUE','AAAAAI NO RESPONSE UPDATE STATUS',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NEEDFLAG == 'TRUE' & newdata$ASSISTANCEFLAG == 'TRUE','AAAAAJ NEED ASSISTANCE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOTFLAG == 'TRUE' & newdata$RESPONDEDFLAG == 'TRUE','AAAAAK NOT RESPONDED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOTFLAG == 'TRUE' & newdata$RESPONDEDFLAG == 'TRUE' & newdata$REQUESTFLAG == 'TRUE','AAAAAL NOT RESPONDED REQUEST',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CANYOUFLAG == 'TRUE' & newdata$LETMEKNOWFLAG == 'TRUE' & newdata$STATUSFLAG == 'TRUE','AAAAAM CAN YOU LET ME KNOW STATUS',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$LETMEKNOWFLAG == 'TRUE' & newdata$STATUSFLAG == 'TRUE','AAAAAN LET ME KNOW STATUS',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$LETMEKNOWFLAG == 'TRUE' & newdata$PROBLEMFLAG == 'TRUE' & newdata$STATUSFLAG == 'TRUE','AAAAAO LET ME KNOW PROBLEM STATUS',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$STILLFLAG == 'TRUE' & newdata$DOESNOTFLAG == 'TRUE' & newdata$WORKFLAG == 'TRUE','AAAAAP STILL DOESNOT WORK',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$WILLANYONEFLAG == 'TRUE' & newdata$RESPONDFLAG == 'TRUE','AAAAAQ WILL ANYONE RESPOND',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$WILLANYONEFLAG == 'TRUE' & newdata$RESPONDFLAG == 'TRUE' & newdata$REQUESTFLAG == 'TRUE','AAAAAR WILL ANYONE RESPOND REQUEST',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$RESPONDFLAG == 'TRUE' & newdata$REQUESTFLAG == 'TRUE','AAAAAS RESPOND REQUEST',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$REQUESTFLAG == 'TRUE' & newdata$STATUSFLAG == 'TRUE','AAAAAT REQUEST STATUS',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$UNABLEFLAG == 'TRUE' & newdata$GETFLAG == 'TRUE' & newdata$RESPONSEFLAG == 'TRUE','AAAAAU UNABLE TO GET RESPONSE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$PROBLEMFLAG == 'TRUE' & newdata$NEEDASSISTANCEFLAG == 'TRUE','AAAAAV PROBLEM NEED ASSISTANCE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOBODYHASFLAG == 'TRUE' & newdata$RESPONDEDFLAG == 'TRUE','AAAAAW NOBODY HAS RESPONDED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CANYOUFLAG == 'TRUE' & newdata$UPDATEFLAG == 'TRUE' & newdata$STATUSFLAG == 'TRUE','AAAAAX CAN YOU UPDATE STATUS',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CANYOUFLAG == 'TRUE' & newdata$UPDATEFLAG == 'TRUE' & newdata$PROBLEMFLAG == 'TRUE' & newdata$STATUSFLAG == 'TRUE','AAAAAY CAN YOU UPDATE PROBLEM STATUS',newdata$KEYWORDVAR)
#newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$UPDATEFLAG == 'TRUE' & newdata$STATUSFLAG == 'TRUE','AAAAAZ UPDATE STATUS',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CANYOUFLAG == 'TRUE' & newdata$STILLFLAG == 'TRUE' & newdata$NOTFLAG == 'TRUE' & newdata$WORKINGFLAG == 'TRUE','AAAABA STILL NOT WORKING',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$YETTOGETFLAG == 'TRUE' & newdata$RESPONSEFLAG == 'TRUE','AAAABB YET TO GET RESPONSE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$UPDATEFLAG == 'TRUE' & newdata$TICKETFLAG == 'TRUE' & newdata$STATUSFLAG == 'TRUE','AAAABC UPDATE TICKET STATUS',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOTFLAG == 'TRUE' & newdata$RESPONDINGFLAG == 'TRUE' & newdata$UPDATEFLAG == 'TRUE' & newdata$STATUSFLAG == 'TRUE','AAAABD NOT RESPONDING UPDATE STATUS',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CANYOUFLAG == 'TRUE' & newdata$RESPONDFLAG == 'TRUE','AAAABE CAN YOU RESPOND',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CANFLAG == 'TRUE' & newdata$SOMEONEFLAG == 'TRUE' & newdata$HELPFLAG == 'TRUE' & newdata$RESOLVINGFLAG == 'TRUE' & newdata$ISSUEFLAG == 'TRUE','AAAABF CAN SOMEONE HELP RESOLVING ISSUE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HELPFLAG == 'TRUE' & newdata$RESOLVINGFLAG == 'TRUE' & newdata$ISSUEFLAG == 'TRUE','AAAABG HELP RESOLVING ISSUE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & (newdata$ONGOINGFLAG == 'TRUE' | newdata$CONTINUOUSFLAG == 'TRUE' | newdata$PROLONGFLAG == 'TRUE') & newdata$ISSUEFLAG == 'TRUE','AAAABH ONGOING ISSUE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOFLAG == 'TRUE' & newdata$PROPERFLAG == 'TRUE' & newdata$RESPONSEFLAG == 'TRUE','AAAABI NO PROPER RESPONSE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$UNABLEFLAG == 'TRUE' & newdata$PROCEEDFLAG == 'TRUE','AAAABJ UNABLE TO PROCEED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$TAKINGFLAG == 'TRUE' & newdata$SOLONGFLAG == 'TRUE' & newdata$CLOSEFLAG == 'TRUE','AAAABK TAKING SO LONG TO CLOSE',newdata$KEYWORDVAR)
#newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$WASNOTFLAG == 'TRUE' & newdata$ABLEFLAG == 'TRUE' & newdata$REACHFLAG == 'TRUE','AAAABL WAS NOT ABLE TO REACH',newdata$KEYWORDVAR)
#newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CALLFLAG == 'TRUE' & newdata$DIDNOTFLAG == 'TRUE' & newdata$PICKUPFLAG == 'TRUE','AAAABM CALL DID NOT PICK UP',newdata$KEYWORDVAR)
#newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$WAITINGFLAG == 'TRUE' & newdata$USERFLAG == 'TRUE' & newdata$RESPONSEFLAG == 'TRUE','AAAABN WAITING FOR USER RESPONSE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOTFLAG == 'TRUE' & newdata$COMPLETEDFLAG == 'TRUE','AAAABO NOT COMPLETED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$TICKETFLAG == 'TRUE' & newdata$CLOSEDFLAG == 'TRUE' & newdata$WITHOUTFLAG == 'TRUE' & newdata$RESOLVINGFLAG == 'TRUE','AAAABP TICKET CLOSED WITHOUT RESOLVING',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$PENDINGFLAG == 'TRUE' & newdata$TICKETFLAG == 'TRUE','AAAABQ PENDING TICKET',newdata$KEYWORDVAR)
#newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$UNABLEFLAG == 'TRUE' & newdata$REACHFLAG == 'TRUE','AAAABR UNABLE TO REACH',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOTFLAG == 'TRUE' & newdata$CONNECTINGFLAG == 'TRUE','AAAABS NOT CONNECTING',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOTFLAG == 'TRUE' & newdata$HAPPYFLAG == 'TRUE','AAAABT NOT HAPPY',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOTFLAG == 'TRUE' & newdata$WORKINGFLAG == 'TRUE','AAAABU NOT WORKING',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$DONOTFLAG == 'TRUE' & newdata$HAVEFLAG == 'TRUE' & newdata$PROPERFLAG == 'TRUE' & newdata$RESPONSEFLAG == 'TRUE','AAAABV DO NOT HAVE PROPER RESPONSE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$REQUESTFLAG == 'TRUE' & newdata$RESPONSEFLAG == 'TRUE','AAAABW REQUEST RESPONSE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$TAKINGFLAG == 'TRUE' & newdata$SOLONGFLAG == 'TRUE' & newdata$RESOLVEFLAG == 'TRUE','AAAABX TAKING SO LONG TO RESOLVE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HAVEFLAG == 'TRUE' & newdata$NOTFLAG == 'TRUE' & newdata$RESPONDEDFLAG == 'TRUE','AAAABY HAVE NOT RESPONDED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HAVEFLAG == 'TRUE' & newdata$NOTFLAG == 'TRUE' & newdata$RESPONDEDFLAG == 'TRUE' & newdata$REQUESTFLAG == 'TRUE','AAAABZ HAVE NOT RESPONDED REQUEST',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HAVEFLAG == 'TRUE' & newdata$NOTFLAG == 'TRUE' & newdata$UPDATEDFLAG == 'TRUE' & newdata$REQUESTFLAG == 'TRUE','AAACAA HAVE NOT UPDATED REQUEST',newdata$KEYWORDVAR)
#newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$UNABLEFLAG == 'TRUE' & newdata$INSTALLFLAG == 'TRUE','AAACAB UNABLE TO INSTALL',newdata$KEYWORDVAR)
#newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$UNABLEFLAG == 'TRUE' & newdata$DOWNLOADFLAG == 'TRUE','AAACAC UNABLE TO DOWNLOAD',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HORRIBLEFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE' & newdata$PROVIDEDFLAG == 'TRUE','AAACAD HORRIBLE CUSTOMER SERVICE PROVIDED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$POORFLAG == 'TRUE' & newdata$ASSISTANCEFLAG == 'TRUE' & newdata$PROVIDEDFLAG == 'TRUE','AAACAE POOR ASSISTANCE PROVIDED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOTFLAG == 'TRUE' & newdata$SATISFIEDFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AAACAF NOT SATISFIED SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOTFLAG == 'TRUE' & newdata$SATISFIEDFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AAACAG NOT SATISFIED CUSTOMER SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$UNHAPPYFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AAACAH UNHAPPY CUSTOMER SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOTFLAG == 'TRUE' & newdata$HAPPYFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AAACAI NOT HAPPY CUSTOMER SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$NOTFLAG == 'TRUE' & newdata$HAPPYFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AAACAJ NOT HAPPY SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$AWFULFLAG == 'TRUE','AAACAK AWFUL',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$BADFLAG == 'TRUE','AAACAL BAD',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$DISAPPOINTEDFLAG == 'TRUE','AAACAM DISAPPOINTED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$DISATISFIEDFLAG == 'TRUE','AAACAN DISATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HORRIBLEFLAG == 'TRUE','AAACAO HORRIBLE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$IRRITATINGFLAG == 'TRUE','AAACAP IRRITATING',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$POORFLAG == 'TRUE','AAACAQ POOR',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$TERRIBLEFLAG == 'TRUE','AAACAR TERRIBLE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$UNSATISFIEDFLAG == 'TRUE','AAACAS UNSATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$UNHAPPYFLAG == 'TRUE','AAACAT UNHAPPY',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$VERYBADFLAG == 'TRUE','AAACAU VERY BAD',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$VERYUNHAPPYFLAG == 'TRUE','AAACAV VERY UNHAPPY',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$VERYUNSATISFIEDFLAG == 'TRUE','AAACAW VERY UNSATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$VERYDISATISFIEDFLAG == 'TRUE','AAACAX VERY DISATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$WORSTFLAG == 'TRUE','AAACAY WORST',newdata$KEYWORDVAR)


###POSITIVE KEYWORDVAR

newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$AMAZINGFLAG == 'TRUE' & newdata$ASSISTANCEFLAG == 'TRUE' & newdata$SATISFIEDFLAG == 'TRUE','AABAAA AMAZING ASSISTANCE SATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$AMAZINGFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AABAAB AMAZING CUSTOMER SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$AMAZINGFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE' & newdata$SATISFIEDFLAG == 'TRUE','AABAAC AMAZING CUSTOMER SERVICE SATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$AMAZINGFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE' & newdata$SATISFIEDFLAG == 'TRUE','AABAAD AMAZING SERVICE SATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$APPRECIATEFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AABAAE APPRECIATE CUSTOMER SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$APPRECIATEFLAG == 'TRUE' & newdata$HELPFLAG == 'TRUE' & newdata$PROVIDEDFLAG == 'TRUE','AABAAF APPRECIATE HELP PROVIDED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$ASSISTANCEFLAG == 'TRUE' & newdata$VERYFLAG == 'TRUE' & newdata$HELPFULFLAG == 'TRUE','AABAAG ASSISTANCE VERY HELPFUL',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CLOSINGFLAG == 'TRUE' & newdata$TICKETFLAG == 'TRUE' & newdata$SUCCESSFULLYFLAG == 'TRUE','AABAAH CLOSING TICKET SUCCESSFULLY',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CLOSINGFLAG == 'TRUE' & newdata$TICKETFLAG == 'TRUE','AABAAI CLOSING TICKET',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$COMPLETEDFLAG == 'TRUE' & newdata$SUCCESSFULLYFLAG == 'TRUE','AABAAJ COMPLETED SUCCESSFULLY',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$HAPPYFLAG == 'TRUE' & newdata$CLOSINGFLAG == 'TRUE' & newdata$TICKETFLAG == 'TRUE','AABAAK CUSTOMER HAPPY CLOSING TICKET',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE' & newdata$GREATFLAG == 'TRUE' & newdata$SATISFIEDFLAG == 'TRUE','AABAAL CUSTOMER SERVICE GREAT SATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE' & newdata$SATISFIEDFLAG == 'TRUE','AABAAM CUSTOMER SERVICE SATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$GREATFLAG == 'TRUE' & newdata$HELPFLAG == 'TRUE' & newdata$THANKYOUFLAG == 'TRUE','AABAAN GREAT HELP THANK YOU',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$GREATFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE' & newdata$PROVIDEDFLAG == 'TRUE','AABAAO GREAT SERVICE PROVIDED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$GREATFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE' & newdata$SATISFIEDFLAG == 'TRUE','AABAAP GREAT SERVICE SATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$GREATFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE' & newdata$THANKSFLAG == 'TRUE','AABAAQ GREAT SERVICE THANKS',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$GREATFLAG == 'TRUE' & newdata$ASSISTANCEFLAG == 'TRUE' & newdata$SATISFIEDFLAG == 'TRUE','AABAAR GREAT ASSISTANCE SATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$GREATFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AABAAS GREAT CUSTOMER SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HAPPYFLAG == 'TRUE' & newdata$ASSISTANCEFLAG == 'TRUE','AABAAT HAPPY WITH ASSISTANCE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HAPPYFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AABAAU HAPPY WITH CUSTOMER SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HAPPYFLAG == 'TRUE' & newdata$GREATFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AABAAV HAPPY WITH GREAT CUSTOMER SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HAPPYFLAG == 'TRUE' & newdata$GREATFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AABAAW HAPPY WITH GREAT SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HAPPYFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AABAAX HAPPY WITH SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$ISSUEFLAG == 'TRUE' & newdata$RESOLVEDFLAG == 'TRUE' & newdata$SUCCESSFULLYFLAG == 'TRUE','AABAAY ISSUE RESOLVED SUCCESSFULLY',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$ISSUEFLAG == 'TRUE' & newdata$RESOLVEDFLAG == 'TRUE','AABAAZ ISSUE RESOLVED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$ASSISTANCEFLAG == 'TRUE','AABABA THANK YOU FOR ASSISTANCE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$CONFIRMATIONFLAG == 'TRUE','AABABB THANK YOU FOR CONFIRMATION',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$CONFIRMATIONFLAG == 'TRUE' & newdata$CLOSINGFLAG == 'TRUE' & newdata$TICKETFLAG == 'TRUE','AABABC THANK YOU FOR CONFIRMATION CLOSING TICKET',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$HELPFLAG == 'TRUE','AABABD THANK YOU FOR HELP',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$PROGRESSFLAG == 'TRUE' & newdata$UPDATEFLAG == 'TRUE','AABABE THANK YOU FOR PROGRESS UPDATE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$QUICKFLAG == 'TRUE' & newdata$SUPPORTFLAG == 'TRUE','AABABF THANK YOU FOR QUICK SUPPORT',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$RESOLUTIONFLAG == 'TRUE','AABABG THANK YOU FOR RESOLUTION',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$RESOLVINGFLAG == 'TRUE' & newdata$ISSUEFLAG == 'TRUE','AABABH THANK YOU FOR RESOLVING ISSUE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AABABI THANK YOU FOR SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$STATUSFLAG == 'TRUE' & newdata$UPDATEFLAG == 'TRUE','AABABJ THANK YOU FOR STATUS UPDATE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$SUPPORTFLAG == 'TRUE','AABABK THANK YOU FOR SUPPORT',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$UPDATEFLAG == 'TRUE','AABABL THANK YOU FOR UPDATE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE' & newdata$QUICKFLAG == 'TRUE' & newdata$SOLUTIONFLAG == 'TRUE','AABABM THANK YOU FOR QUICK SOLUTION',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKSFLAG == 'TRUE' & newdata$HELPFLAG == 'TRUE','AABABN THANKS FOR HELP',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKSFLAG == 'TRUE' & newdata$QUICKFLAG == 'TRUE' & newdata$TURNFLAG == 'TRUE' & newdata$AROUNDFLAG == 'TRUE','AABABO THANKS FOR QUICK TURN AROUND',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKSFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AABABP THANKS FOR SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKSFLAG == 'TRUE' & newdata$UPDATEFLAG == 'TRUE','AABABQ THANKS FOR UPDATE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$WONDERFULFLAG == 'TRUE' & newdata$ASSISTANCEFLAG == 'TRUE' & newdata$SATISFIEDFLAG == 'TRUE','AABABR WONDERFUL ASSISTANCE SATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$WONDERFULFLAG == 'TRUE' & newdata$CUSTOMERFLAG == 'TRUE' & newdata$SERVICEFLAG == 'TRUE','AABABS WONDERFUL CUSTOMER SERVICE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$AMAZINGFLAG == 'TRUE','AABABT AMAZING',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$APPRECIATEFLAG == 'TRUE','AABABU APPRECIATE',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$EXCELLENTFLAG == 'TRUE','AABABV EXCELLENT',newdata$KEYWORDVAR)
#newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$GOODFLAG == 'TRUE','AABABW GOOD',newdata$KEYWORDVAR)
#newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HELPFLAG == 'TRUE','AABABX HELP',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HELPFULFLAG == 'TRUE','AABABY HELPFUL',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$HAPPYFLAG == 'TRUE','AABABZ HAPPY',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$GREATFLAG == 'TRUE','AABACA GREAT',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$SATISFIEDFLAG == 'TRUE','AABACB SATISFIED',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKSFLAG == 'TRUE','AABACC THANKS',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$THANKYOUFLAG == 'TRUE','AABACD THANK YOU',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & newdata$WONDERFULFLAG == 'TRUE','AABACE WONDERFUL',newdata$KEYWORDVAR)
newdata$KEYWORDVAR = ifelse(newdata$KEYWORDVAR == '' & (newdata$AMAZINGFLAG == 'TRUE' | newdata$GOODFLAG == 'TRUE' | newdata$APPRECIATEFLAG == 'TRUE'| newdata$ASSISTANCEFLAG == 'TRUE' | newdata$GREATFLAG == 'TRUE' | newdata$THANKYOUFLAG == 'TRUE' | newdata$HELPFULFLAG == 'TRUE' | newdata$WONDERFULFLAG == 'TRUE' | newdata$HAPPYFLAG == 'TRUE' | newdata$VERYGOODFLAG == 'TRUE' | newdata$VERYHAPPYFLAG == 'TRUE' | newdata$EXCELLENTFLAG == 'TRUE') & (newdata$HELPFULFLAG == 'TRUE' | newdata$HELPFLAG == 'TRUE' | newdata$WORKFLAG == 'TRUE' | newdata$JOBFLAG == 'TRUE' | newdata$EXPERIENCEFLAG == 'TRUE' | newdata$SERVICEFLAG == 'TRUE' | newdata$ASSISTANCEFLAG == 'TRUE' | newdata$PERFORMANCEFLAG == 'TRUE' | newdata$WORKINGFLAG == 'TRUE' | newdata$SATISFIEDFLAG == 'TRUE' | newdata$RESPONSEFLAG == 'TRUE' | newdata$STATUSFLAG == 'TRUE' | newdata$RESPONSEFLAG == 'TRUE' | newdata$RESPONDEDFLAG == 'TRUE' | newdata$RESPONDINGFLAG == 'TRUE' | newdata$UPDATEFLAG == 'TRUE'),'AABACF GOOD CUSTOMER SERVICE',newdata$KEYWORDVAR)###KEYWORDVAR_O1

newdata$KEYWORDVAR_O1  = 0

newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR ==  'AAAAAA WILL YOU RESPOND',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAB RESPOND POOR CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAC RESPOND POOR SERVICE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAD POOR CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAE WHY WONT ANYONE RESPOND',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAF WHY WONT ANYONE RESPOND REQUEST',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAG CANNOT GET RESPONSE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAH REQUEST STATUS CANNOT GET RESPONSE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAI NO RESPONSE UPDATE STATUS',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAJ NEED ASSISTANCE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAK NOT RESPONDED',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAL NOT RESPONDED REQUEST',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAM CAN YOU LET ME KNOW STATUS',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAN LET ME KNOW STATUS',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAO LET ME KNOW PROBLEM STATUS',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAP STILL DOESNOT WORK',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAQ WILL ANYONE RESPOND',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAR WILL ANYONE RESPOND REQUEST',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAS RESPOND REQUEST',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAT REQUEST STATUS',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAU UNABLE TO GET RESPONSE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAV PROBLEM NEED ASSISTANCE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAW NOBODY HAS RESPONDED',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAX CAN YOU UPDATE STATUS',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAY CAN YOU UPDATE PROBLEM STATUS',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAAAZ UPDATE STATUS',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABA STILL NOT WORKING',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABB YET TO GET RESPONSE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABC UPDATE TICKET STATUS',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABD NOT RESPONDING UPDATE STATUS',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABE CAN YOU RESPOND',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABF CAN SOMEONE HELP RESOLVING ISSUE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABG HELP RESOLVING ISSUE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABH ONGOING ISSUE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABI NO PROPER RESPONSE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABJ UNABLE TO PROCEED',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABK TAKING SO LONG TO CLOSE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABL WAS NOT ABLE TO REACH',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABM CALL DID NOT PICK UP',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABN WAITING FOR USER RESPONSE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABO NOT COMPLETED',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABP TICKET CLOSED WITHOUT RESOLVING',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABQ PENDING TICKET',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABR UNABLE TO REACH',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABS NOT CONNECTING',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABT NOT HAPPY',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABU NOT WORKING',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABV DO NOT HAVE PROPER RESPONSE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABW REQUEST RESPONSE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABX TAKING SO LONG TO RESOLVE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABY HAVE NOT RESPONDED',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAAABZ HAVE NOT RESPONDED REQUEST',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAA HAVE NOT UPDATED REQUEST',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAB UNABLE TO INSTALL',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAC UNABLE TO DOWNLOAD',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAD HORRIBLE CUSTOMER SERVICE PROVIDED',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAE POOR ASSISTANCE PROVIDED',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAF NOT SATISFIED SERVICE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAG NOT SATISFIED CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAH UNHAPPY CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAI NOT HAPPY CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAJ NOT HAPPY SERVICE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAK AWFUL',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAL BAD',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAM DISAPPOINTED',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAN DISATISFIED',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAO HORRIBLE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAP IRRITATING',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAQ POOR',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAR TERRIBLE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAS UNSATISFIED',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAT UNHAPPY',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAU VERY BAD',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAV VERY UNHAPPY',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAW VERY UNSATISFIED',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAX VERY DISATISFIED',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAY WORST',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAZ BAD CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 == 0 & newdata$KEYWORDVAR == 'AAACAZ BAD',1,newdata$KEYWORDVAR_O1)
newdata$KEYWORDVAR_O1 = ifelse(newdata$KEYWORDVAR_O1 != 0,newdata$KEYWORDVAR_O1,0)


###KEYWORDVAR_O2

newdata$KEYWORDVAR_O2  = 0
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAA AMAZING ASSISTANCE SATISFIED',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAB AMAZING CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAC AMAZING CUSTOMER SERVICE SATISFIED',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAD AMAZING SERVICE SATISFIED',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAE APPRECIATE CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAF APPRECIATE HELP PROVIDED',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAG ASSISTANCE VERY HELPFUL',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAH CLOSING TICKET SUCCESSFULLY',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAI CLOSING TICKET',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAJ COMPLETED SUCCESSFULLY',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAK CUSTOMER HAPPY CLOSING TICKET',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAL CUSTOMER SERVICE GREAT SATISFIED',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAM CUSTOMER SERVICE SATISFIED',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAN GREAT HELP THANK YOU',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAO GREAT SERVICE PROVIDED',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAP GREAT SERVICE SATISFIED',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAQ GREAT SERVICE THANKS',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAR GREAT ASSISTANCE SATISFIED',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAS GREAT CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAT HAPPY WITH ASSISTANCE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAU HAPPY WITH CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAV HAPPY WITH GREAT CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAW HAPPY WITH GREAT SERVICE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAX HAPPY WITH SERVICE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAY ISSUE RESOLVED SUCCESSFULLY',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABAAZ ISSUE RESOLVED',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABA THANK YOU FOR ASSISTANCE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABB THANK YOU FOR CONFIRMATION',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABC THANK YOU FOR CONFIRMATION CLOSING TICKET',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABD THANK YOU FOR HELP',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABE THANK YOU FOR PROGRESS UPDATE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABF THANK YOU FOR QUICK SUPPORT',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABG THANK YOU FOR RESOLUTION',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABH THANK YOU FOR RESOLVING ISSUE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABI THANK YOU FOR SERVICE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABJ THANK YOU FOR STATUS UPDATE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABK THANK YOU FOR SUPPORT',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABL THANK YOU FOR UPDATE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABM THANK YOU FOR QUICK SOLUTION',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABN THANKS FOR HELP',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABO THANKS FOR QUICK TURN AROUND',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABP THANKS FOR SERVICE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABQ THANKS FOR UPDATE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABR WONDERFUL ASSISTANCE SATISFIED',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABS WONDERFUL CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABT AMAZING',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABU APPRECIATE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABV EXCELLENT',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABW GOOD',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABX HELP',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABY HELPFUL',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABABZ HAPPY',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABACA GREAT',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABACB SATISFIED',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABACC THANKS',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABACD THANK YOU',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABACE WONDERFUL',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 == 0 & newdata$KEYWORDVAR == 'AABACF GOOD CUSTOMER SERVICE',1,newdata$KEYWORDVAR_O2)
newdata$KEYWORDVAR_O2 = ifelse(newdata$KEYWORDVAR_O2 != 0,newdata$KEYWORDVAR_O2,0)


setwd("D:/R Output files")
write.csv(newdata,file="newdata_output3.csv")

